<?php

namespace Betta\Filament\FqnSettings\Pages;

use BackedEnum;
use Betta\Filament\FqnSettings\Pages\Concerns\CanExpandSchema;
use Betta\Filament\FqnSettings\Pages\Concerns\CanSaveSettings;
use Betta\Filament\FqnSettings\Pages\Concerns\HasActions;
use Betta\Filament\FqnSettings\Pages\Concerns\HasColumns;
use Betta\Filament\FqnSettings\Pages\Concerns\HasForm;
use Betta\Filament\FqnSettings\Pages\Concerns\HasFqnSettingComponents;
use Betta\Filament\FqnSettings\Pages\Concerns\HasNavigation;
use Betta\Filament\FqnSettings\Pages\Concerns\HasSettingsSlug;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Pages\Page;
use Filament\Schemas\Schema;

/**
 * @property Form $form
 */
class SettingPage extends Page implements HasForms, \Filament\Actions\Contracts\HasActions
{
    use CanExpandSchema;
    use CanSaveSettings;
    use HasActions;
    use HasColumns;
    use HasForm;
    use HasFqnSettingComponents;
    use HasNavigation;
    use HasSettingsSlug;

    protected array $settingComponents = [];

    protected static string $view = 'filament-fqn-settings::filament.pages.page';

    protected static string|null $navigationIcon = 'heroicon-o-cog-6-tooth';

    public ?array $data;

    public function mount(): void
    {
        $this->form->fill([
            ...$this->fillAdditionalData(),
            ...$this->getComponentData(),
        ]);
    }
    
    public static function getNavigationSort(): ?int
    {
        return parent::getNavigationSort(); // TODO: Change the autogenerated stub
    }
}
